#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend all-as.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 524428-web-01 18.233.63.50:80
        server 524428-web-02 54.236.49.251:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
