#!/bin/bash
files="0-current_working_directory 102-tree 11-lists 14-copy_html 3-listfiles 6-firstdirectory 9-firstdirdeletion 100-lets_move 103-commas 12-file_type 1-listit 4-listmorefiles 7-movethatfile README.md 101-clean_emacs 10-back 13-symbolic_link 2-bring_me_home 5-listfilesdigitonly 8-firstdelete"

for file in $files; do
    echo "" >> "$file"
done

